
include "FM.mzn";


constraint isActivated[1] == true;
constraint isIncluded[1] == true;



constraint isActivated[2] == true;
constraint isIncluded[2] == true;



constraint isActivated[3] == true;
constraint isIncluded[3] == true;



constraint isActivated[4] == true;
constraint isIncluded[4] == true;







constraint isActivated[7] == true;
constraint isIncluded[7] == true;



constraint isActivated[8] == true;
constraint isIncluded[8] == false;



constraint isActivated[9] == true;
constraint isIncluded[9] == false;



constraint isActivated[10] == true;
constraint isIncluded[10] == false;



constraint isActivated[11] == true;
constraint isIncluded[11] == true;



constraint isActivated[12] == true;
constraint isIncluded[12] == true;









constraint isActivated[16] == true;
constraint isIncluded[16] == true;



constraint isActivated[17] == true;
constraint isIncluded[17] == false;



constraint isActivated[18] == true;
constraint isIncluded[18] == false;



constraint isActivated[19] == true;
constraint isIncluded[19] == false;



constraint isActivated[20] == true;
constraint isIncluded[20] == false;



constraint isActivated[21] == true;
constraint isIncluded[21] == false;



constraint isActivated[22] == true;
constraint isIncluded[22] == false;





constraint isActivated[24] == true;
constraint isIncluded[24] == true;





constraint isActivated[26] == true;
constraint isIncluded[26] == false;



constraint isActivated[27] == true;
constraint isIncluded[27] == false;



constraint isActivated[28] == true;
constraint isIncluded[28] == false;



constraint isActivated[29] == true;
constraint isIncluded[29] == false;


