
include "FM.mzn";


constraint isActivated[1] == true;
constraint isIncluded[1] == true;



constraint isActivated[2] == true;
constraint isIncluded[2] == true;



constraint isActivated[3] == true;
constraint isIncluded[3] == true;





constraint isActivated[5] == true;
constraint isIncluded[5] == true;



constraint isActivated[6] == true;
constraint isIncluded[6] == false;



constraint isActivated[7] == true;
constraint isIncluded[7] == true;



constraint isActivated[8] == true;
constraint isIncluded[8] == false;



constraint isActivated[9] == true;
constraint isIncluded[9] == false;



constraint isActivated[10] == true;
constraint isIncluded[10] == false;


















